apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-kraft
  namespace: kafka
spec:
  kafka:
    version: 4.1.0
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
    config:
      process.roles: "controller,broker"
      controller.listener.names: CONTROLLER
      inter.broker.listener.name: INTERNAL
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: persistent-claim
      size: 10Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kraft-nodes
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-kraft
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: persistent-claim
    size: 10Gi

