apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-kraft
  namespace: kafka
spec:
  kafka:
    version: 4.1.0
    replicas: 3
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
    storage:
      type: persistent-claim
      size: 10Gi
    config:
      process.roles: "controller,broker"
      controller.listener.names: CONTROLLER
      inter.broker.listener.name: INTERNAL
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
